STRIPE_PUBLICKEY = "pk_test_51H4dXYKerLxqwoyWog0axDg7RJbvbHAHUzhbft84by1FM0GXwzeVcFylbewLZsL4rFRZKncFSQdYvwCTaRO3ZcFI003FYBgFbE"
STRIPE_SUCCESS_URL = "http://localhost:1313/success"
STRIPE_CANCEL_URL = "http://localhost:1313/"