STRIPE_PUBLICKEY = "pk_test_51H4dXYKerLxqwoyWog0axDg7RJbvbHAHUzhbft84by1FM0GXwzeVcFylbewLZsL4rFRZKncFSQdYvwCTaRO3ZcFI003FYBgFbE"
STRIPE_SUCCESS_URL = "https://neureta-hugo-git-develop.gabygaspar.vercel.app/success"
STRIPE_CANCEL_URL = "https://neureta-hugo-git-develop.gabygaspar.vercel.app/"