---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/instructors
  label: Instructors
  create: documents
  match: "**/*"
  exclude: index.md
  new_doc_ext: md
  templates:
  - instructor
- type: heading
  label: eCommerce
- type: directory
  path: content/courses
  label: Courses
  create: documents
  match: "**/*"
  exclude: _index.md
  new_doc_ext: md
  templates:
  - course
- type: directory
  path: content/store
  label: Tienda
  create: documents
  match: "**/*"
  exclude: _index.md
  new_doc_ext: md
  templates:
  - product
- type: document
  path: data/opening-dates.yml
  label: Opening Dates
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
