STRIPE_PUBLICKEY = "pk_live_51H4dXYKerLxqwoyWZP652Ck8DuIIbe3oWvVTxK4KhmuJdN0OTmNrGi5GRTQzVCvMV3naVi9o48vIo1qkKdrAG9nO00uLLnL8E0"
STRIPE_SUCCESS_URL = "https://neureta.com.mx/success"
STRIPE_CANCEL_URL = "https://neureta.com.mx/"