---
label: Product
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Name of product
- name: featured_image
  type: file
  config:
    maxSize: 64
  label: Featured Image
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
    max: 320
    min: 90
  label: Description
- name: type
  type: select
  default: []
  config:
    required: false
    options:
    - book
    - materials
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type of Product
- name: price
  type: number
  description: ''
  default: 0
  required: true
  config:
    min: 0
    max: 
    step: 
    required: true
  label: Price
pages:
- content/products/estimular-la-velocidad-de-procesamiento.md
- content/products/neuroeducacion-y-lectura.md
