---
label: Product
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Name of product
- name: featured_image
  type: file
  config:
    maxSize: 64
  label: Featured Image
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
    max: 320
    min: 90
  label: Description
- name: type
  type: select
  default: []
  config:
    required: false
    options:
    - book
    - materials
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type of Product
- name: price
  type: number
  description: ''
  default: 0
  required: true
  config:
    min: 0
    max: 
    step: 
    required: true
  label: Price
- name: stripe_id
  type: text
  config:
    required: true
  label: Stripe Price ID
pages:
- content/store/adecuaciones-curriculares.guia-para-los-profesores-tutores-de-educacion-primaria-y-educacion-especial.md
- content/store/alumnos-distraidos-inquietos-e-impulsivos-tda-h.md
- content/store/autismo-de-la-comprension-teorica-a-la-intervencion-educativa.md
- content/store/como-estimular-el-cerebro-del-nino.md
- content/store/comunicacion-social-para-ninos-con-autismo-y-otras-dificultades-del-desarrollo.md
- content/store/deficit-de-atencion-con-hiperactividad.manual-para-padres-y-educadores.md
- content/store/disciplina-sin-lagrimas.una-guia-imprescindible-para-orientar-y-alimentar-el-desarrollo-mental-de-tu-hijo.md
- content/store/ejercicios-para-la-recuperacion-de-la-dislexia-4.md
- content/store/el-cerebro-infantil-y-adolescente.claves-y-secretos-de-la-neuroeducacion.md
- content/store/el-nino-que-habla-bien.el-lenguaje-en-el-preescolar.md
- content/store/el-tdah-no-es-una-condicion-negativa.md
- content/store/estimular-la-atencion.nivel-4.md
- content/store/estimular-la-orientacion-espacial-2.md
- content/store/evaluacion-neuropsicologica-de-los-procesos-atencionales.md
- content/store/familia-de-ninos-con-tea-programa-de-psicoeducacion-emocional-y-apoyo-mutuo.md
- content/store/guia-de-intervencion-logopedica-en-funciones-ejecutivas.md
- content/store/guia-de-intervencion-logopedica-en-los-trastornos-de-autismo.md
- content/store/guia-de-intervencion-logopedica-en-sindrome-de-down.md
- content/store/guia-de-intervencion-logopedica-en-trastornos-por-deficit-de-atencion-e-hiperactividad.md
- content/store/guia-de-intervencion-logopedicas-en-las-dislalias.md
- content/store/intervencion-educativa-en-el-tdah.md
- content/store/la-disgrafia.md
- content/store/la-dislexia-origen-diagnostico-y-recuperacion.md
- content/store/los-ninos-pequenos-con-autismo.soluciones-practicas-para-problemas-cotidianos.md
- content/store/manual-de-juegos-para-ninos-con-autismo.md
- content/store/mejora-de-funciones-ejecutivas-conductuales.programa-preventivo.md
- content/store/mejora-de-funciones-ejecutivas-y-conductuales.programa-preventivo.md
- content/store/programa-de-intervencion-cognitivo-conductual-para-ninos-con-deficit-de-atencion-con-hiperactividad.md
- content/store/trastornos-de-espectro-autista-de-alto-funcionamiento.otra-forma-de-aprender.md
