---
label: Product
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Name of product
- name: featured_image
  type: file
  config:
    maxSize: 64
  label: Featured Image
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
    max: 320
    min: 90
  label: Description
- name: type
  type: select
  default: []
  config:
    required: false
    options:
    - book
    - materials
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type of Product
- name: price
  type: number
  description: ''
  default: 0
  required: true
  config:
    min: 0
    max: 
    step: 
    required: true
  label: Price
pages:
- content/products/comprender-mejor-la-dislexia.md
- content/products/crear-escuela-creando-puentes-entre-la-neurociencia-y-el-aula.md
- content/products/cuentos-para-portarse-bien-en-el-cole.md
- content/products/dificultades-especificas-de-lecto-escritura-volumen-1.md
- content/products/ejercicios-para-la-recuperacion-de-la-dislexia-1.md
- content/products/ejercicios-para-la-recuperacion-de-la-dislexia-2.md
- content/products/ejercicios-para-la-recuperacion-de-la-dislexia.md
- content/products/el-acceso-al-curriculo-por-alumnos-con-trastornos-del-espectro-del-autismo-utilizando-programas-teacch-para-favorecer-la-inclusion.md
- content/products/el-cerebro-del-nino-explicado-para-padres.md
- content/products/entrenamiento-de-la-conciencia-fonologica.md
- content/products/estimular-la-velocidad-de-procesamiento.md
- content/products/manual.los-sonidos-de-las-palabras.md
- content/products/neuroeducacion-y-funciones-ejecutivas.md
- content/products/neuroeducacion-y-lectura.md
- content/products/superar-la-dislexia.una-experiencia-personal-a-traves-de-la-investigacion.md
- content/products/velocidad-de-procesamiento-3.md
